### ISSUE TITLE
How did you get so darn cool?

### ISSUE THREAD

**Issue by JJJ** [rmccue/ama#1]
You work on many of the most awesome and useful tools on the modern web. How did you get here? How do you maintain momentum in the face of adversity? Do you spell "color" with a "u"?

**Comment by rmccue** [comment]
> You work on many of the most awesome and useful tools on the modern web. How did you get here? How do you maintain momentum in the face of adversity?

I'm a sucker for punishment. Mainly I keep working on stuff because no one else wants to, and if I don't do it, no one will.

> Do you spell "color" with a "u"?

colour (not color), metre (not meter, not mile), spelt (not spelled), roundabout (not rotary).

**Comment by JJJ** [comment]
A+++ REPLY. WILL DEFINITELY ASK ANOTHER AROUND THE 100 MARK.

**Comment by Japh** [comment]
:joy:
