### ISSUE TITLE
Are you planning to push REST API in WordPress further?

### ISSUE THREAD

**Issue by slaFFik** [rmccue/ama#11]
Or are you "done" with it, because (perhaps) of the February meeting with Matt?

**Comment by rmccue** [comment]
I totally missed this question previously, so sorry! Definitely planning on continuing to push the API, but I'm super busy, and it really needs my full time on it. I'm hoping I'll get to a point where I have the time for it soon, however it's tough to balance with other work.

Matt and I have different opinions, but I don't see any huge problems with that. We just need to reach a mutual understanding. :)
