### ISSUE TITLE
What is that flying dog drawing you use as your avatar?

### ISSUE THREAD

**Issue by jwenerd** [rmccue/ama#12]
What is that flying dog drawing you use as your avatar? Is it from a cartoon/comic?

**Comment by rmccue** [comment]
It was drawn for me by [First Dog on the Moon](https://firstdogonthemoon.com.au/), political cartoonist for The Guardian Australia (previously at Crikey). He put out an offer to redraw avatars as cartoon animals, and I put my hand up. :)
