### ISSUE TITLE
How do you consume content?

### ISSUE THREAD

**Issue by Japh** [rmccue/ama#2]
Given the vast volume of content you must consume to keep up with the various projects you're involved with (WordPress core, REST API, various Human Made work, etc.), how do you consume all of this project-meta while still actually having time to work on the projects themselves?

**Comment by rmccue** [comment]
I struggle. Mostly Slack for internal discussions, as I read all messages for every room I'm in. Outside of that, email, although that's mostly a crapshoot and I don't really get much done with that.

Any suggestions? :)

**Comment by Japh** [comment]
I think everyone struggles with this. If there's anyone who doesn't... they must be magic.
