### ISSUE TITLE
About Developer Setup and Tools

### ISSUE THREAD

**Issue by dipakcg** [rmccue/ama#21]
Hey Ryan,

I am very curious to know what kind of dev setup you've? What IDE, Apps / Softwares, Productivity tools, Project management methods you use in your day-to-day life? How do you manage multiple projects / products at the same time? Your desk setup pic(s) if possible?

Is there any specific advice you would like to give fellow WordPress Developers?

Thanks in advance!

**Comment by rmccue** [comment]
👋 Thanks for asking, here's a bit of a dump.

## Tools
### Editor

I use VS Code primarily, with a setup very similar to [John's](https://johnblackbourn.com/my-code-extensions/). In particular, I have:

* Base16 Eighties (Base16 handles my colour scheme in a consistent way across all my tools)
* Color Info
* Dash
* ESLint
* GitLens (mostly disabled, I only have this for the hover views and status bar)
* Header Source Switch (for a hotkey to switch between .js and .css files of the same name for React projects)
* IntelliSense for CSS class names in HTML
* Nasc VSCode Touchbar
* Path Intellisense
* PHP DocBlocker
* PHP Intelephense
* Sublime Text Keymap
* Trailing Spaces
* WhiteViz

<img width="1552" alt="Screen Shot 2019-07-10 at 13 39 56" src="https://user-images.githubusercontent.com/21655/60969752-3a0d3f00-a318-11e9-88b2-67ff0ebe354d.png">


### Terminal

I use Hyper with tmux (+tmuxinator), fish, and Powerline. This uses Base16 for the colour scheme as well.

<img width="1552" alt="Screen Shot 2019-07-10 at 13 39 42" src="https://user-images.githubusercontent.com/21655/60969781-4f826900-a318-11e9-92b1-30cb7721a91b.png">

### Other

Overall, I have my desktop set up with 4 fixed spaces in macOS. They have tools permanently assigned, plus hotkeys:

* Space 1: Firefox, Ctrl-1
* Space 2: VS Code, Ctrl-2
* Space 3: Hyper, Ctrl-3
* Space 4: Other tools (Slack, Spotify, etc), Ctrl-4

## Process

Code projects and HM meta tasks on are pretty much all managed in GitHub. We also use ZenHub for advanced project management and cross-repo management (e.g. for Altis, we have a ZenHub board with 20 repos).

Communication at Human Made mostly happens asynchronously on H2, which is our version of P2 (but built from scratch as a React app). I mostly read this via the email notification integration, powered by [Falcon](https://github.com/rmccue/Falcon). Synchronous communication is in Slack, and we have calls on Zoom.

Other tools we use regularly are Google Docs (for document collaboration), and Workable (for hiring).

I use Trello to manage meta tasks, with Backlog, Next Week, This Week, and Complete columns. Everything in "This Week" is tagged with a day to ensure I have time specifically allocated for it.

## Workspace

I work from a coworking space with a permanent desk, about a 10 min walk from home. I try and keep my desk fairly sparse; this is what it currently looks like, which I'd call cluttered:

![IMG_6445](https://user-images.githubusercontent.com/21655/60976809-4e583880-a326-11e9-9edf-964674912afe.jpg)

----

No specific advice for anyone else; work out what works for you! Happy to answer any follow-ups :)

**Comment by dipakcg** [comment]
That's wonderful! Thanks for taking the time to share 🙂
