### ISSUE TITLE
I have a new idea, and I'd like you to be involved.

### ISSUE THREAD

**Issue by Japh** [rmccue/ama#5]
This is a theoretical... but let's say I have an amazing idea for something WordPress-related that I'd like to build. And I think your skills would be invaluable to my project. How could I actually get you involved?  :smile:

**Comment by rmccue** [comment]
Good luck. :stuck_out_tongue:

I'm pretty overcommitted to projects as is (see #1), so it's unlikely you'd be able to convince me to work on anything. Typically, I'll contribute back to stuff I'm already using, but those are mostly drive-by contributions. I have enough of my own projects eating my time to work on anything else. :)
