### ISSUE TITLE
What is the best piece of advice you have ever been given?

### ISSUE THREAD

**Issue by Luciaisacomputer** [rmccue/ama#9]

**Comment by rmccue** [comment]
Good question, although hard to answer.

The best advice I've been given was simply encouragement from friends and colleagues when I was deciding [whether to leave uni](http://journal.rmccue.io/305/change/). This encouragement was a key part of why I made the decision, and I wouldn't have been able to make it without this support.

I can't really pin down specifically any short, snappy piece of advice, but I do have a quote I love: "Unless someone like you cares an awful lot / Nothing's ever going to get better, it's not." (from The Lorax by Dr Seuss). Every time I look at things that suck, what I really see is that no one has cared about this problem, and it needs someone to care for it.

This leads me to start a lot of projects to fix things that then don't always get the follow-through that they deserve, but part of that is that there are always more problems to solve. My hope with projects is always to kick-off the process of getting other people to care about them. The [Importer](https://github.com/humanmade/WordPress-Importer) is along these lines; it's been neglected for so long, and my hope is that working on it will draw other people to it to continue to improve it even after I've moved on.
